- name: bug
  color: d73a4a
  description: Something isn't working
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: question
  color: d876e3
  description: Further information is requested
- name: wontfix
  color: ffffff
  description: This will not be worked on
- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file
- name: security
  color: ee0701
  description: Security related issue or improvement
- name: performance
  color: 5319e7
  description: Performance improvement or issue
- name: testing
  color: fbca04
  description: Testing related changes
- name: ci
  color: 1d76db
  description: Changes to CI configuration files and scripts
- name: automerge
  color: 0e8a16
  description: Pull requests that can be automatically merged
- name: breaking-change
  color: b60205
  description: Introduces a breaking change
- name: blocked
  color: b60205
  description: Blocked by other work or waiting for something
- name: feature
  color: 0e8a16
  description: New feature implementation
- name: bug-fix
  color: d93f0b
  description: Bug fix implementation
- name: maintenance
  color: c5def5
  description: Repository maintenance
- name: github-actions
  color: 4caf50
  description: Related to GitHub Actions
