name: Branch Protection Check

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'examples/**'

jobs:
  validate:
    name: Validate Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            - feat
            - fix
            - docs
            - style
            - refactor
            - perf
            - test
            - build
            - ci
            - chore
            - revert
          requireScope: false

      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          if [[ ! $BRANCH_NAME =~ ^(feature|bugfix|hotfix|release|docs|refactor|test|ci|chore)/[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Branch names should follow the pattern: feature/my-feature-name"
            exit 1
          fi
          echo "Branch name '$BRANCH_NAME' is valid."
