name: Project Management

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
    - name: Add issue to project
      uses: actions/add-to-project@v1.0.3
      with:
        project-url: https://github.com/orgs/Perun-Engineering/projects/1
        github-token: ${{ secrets.GITHUB_TOKEN }}

  manage-prs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Link PR to issue
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const body = pr.body || '';

          // Look for issue references in PR body
          const issueMatch = body.match(/(?:closes|fixes|resolves)\s+#(\d+)/i);
          if (issueMatch) {
            const issueNumber = issueMatch[1];
            console.log(`PR #${pr.number} references issue #${issueNumber}`);

            // Add comment to issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `🔗 Linked to PR #${pr.number}`
            });
          }

  check-workflows:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4

    - name: Validate workflow files
      run: |
        # Check if any workflow files were modified
        if git diff --name-only origin/main...HEAD | grep -q "^\.github/workflows/"; then
          echo "Workflow files modified, validating..."

          # Basic YAML validation
          for file in .github/workflows/*.yml .github/workflows/*.yaml; do
            if [ -f "$file" ]; then
              echo "Validating $file"
              python -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
            fi
          done

          echo "All workflow files are valid YAML"
        else
          echo "No workflow files modified"
        fi
